#!/usr/bin/env node
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import {guidePages} from './public-content.mjs';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),write=(p,s)=>fs.writeFileSync(path.join(root,p),s);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base='https://thearchitect-max.github.io/MyProjects/';
const links=[['','Overview'],['portfolio.html','Portfolio'],['opportunity.html','Opportunity'],['valuation.html','Valuation'],['evidence.html','Evidence'],['transaction.html','Transaction'],['notice.html','Notice']];
function header(prefix,current){return `<a class="skip" href="#main">Skip to content</a><header><div class="shell nav"><a class="brand" href="${prefix||'./'}" aria-label="THEARCHITECT_MAX portfolio home"><span class="mark">TA</span><span class="brand-copy"><strong>THEARCHITECT_MAX</strong><span>Technology & IP Portfolio</span></span></a><nav class="nav-links" aria-label="Primary navigation">${links.map(([url,label])=>`<a ${url===current?'aria-current="page" ':''}href="${prefix+url||'./'}">${label}</a>`).join('')}</nav></div></header>`}
function footer(prefix){return `<footer class="footer"><div class="shell footer-inner"><div><strong>THEARCHITECT_MAX</strong><p>Technology & IP Portfolio<br>79 individually scoped assets · September 2026</p><div class="footer-links"><a href="${prefix}portfolio.html">Portfolio</a><a href="${prefix}evidence.html">Evidence</a><a href="${prefix}transaction.html">Enquiries</a><a href="${prefix}updates.html">Development review</a><a href="${prefix}commercialization.html">Applications & buyers</a><a href="${prefix}transfer.html">Buyer guide</a><a href="${prefix}assurance.html">Disclosure policy</a><a href="${prefix}notice.html">Important notice</a></div></div><div><p>Seller-side commercial references for professional discussion. Subject to asset-specific diligence and definitive agreement.</p><p>© 2026 THEARCHITECT_MAX. All rights reserved.</p></div></div></footer>`}
const elements=new Map();
function el(id,value=''){const e={innerHTML:'',textContent:'',value,dataset:{},addEventListener(){},querySelectorAll(){return[]}};elements.set(id,e);return e}
const context={console,Intl,URLSearchParams,document:{documentElement:{dataset:{}},getElementById:id=>elements.get(id)||null,querySelector:()=>null},location:{pathname:'/',search:''},fetch:async url=>({ok:true,json:async()=>JSON.parse(read(url.split('?')[0])),text:async()=>read(url.split('?')[0])})};
vm.createContext(context);
let source=read('assets/im.js').replace(/document.readyState==='loading'[\s\S]*?init\(\);\}\)\(\);\s*$/, 'globalThis.api={load,overview,featured,schedule,detail};})();');
vm.runInContext(source,context);
const data=await context.api.load();
let economic=read('assets/economic.js').replace(/document.readyState==='loading'[\s\S]*?init\(\);\}\)\(\);\s*$/, 'globalThis.economic={parse,economicPanel};})();');
vm.runInContext(economic,context);
const economicRows=context.economic.parse(read('assets/asset-economic-valuations.csv'));
const values=new Map(economicRows.map(r=>[r.slug,r]));
const commercial=JSON.parse(read('assets/commercial-context.json'));
for(const family of data.families)if(!commercial.families[family.id])throw Error('Missing public commercial context: '+family.id);
function buyerPanel(a){const c=commercial.families[a.family.id];return `<section class="section public-buyer-context"><p class="eyebrow">Potential buyer fit</p><h2 class="section-title">Commercial context for this asset.</h2><p>Illustrative family-level applications, to be qualified against ${escape(a.ref)} and its stated purpose. These are not verified customer deployments or guaranteed outcomes.</p><div class="detail-commercial-grid"><article class="panel"><h3>Potential counterparties</h3><p>${escape(c.buyers)}.</p><h3>Application context</h3><p>${escape(c.applications)}.</p></article><article class="panel"><h3>Possible buyer benefit</h3><p>${escape(c.benefit)}.</p><h3>Qualification question</h3><p>${escape(c.qualification)}</p></article></div><p class="notice">This public profile describes commercial purpose. Confidential implementation material is outside its scope. Development labels do not establish production readiness, scientific validity or regulatory approval.</p><div class="actions"><a class="btn" href="../../commercialization.html">Commercial applications</a><a class="btn" href="../../transfer.html">Buyer diligence</a><a class="btn" href="../../assurance.html">Disclosure boundaries</a></div></section>`;}
function shell(s,prefix,current){s=s.replace(/<a class="skip"[^>]*>.*?<\/a>/g,'').replace(/<header>[\s\S]*?<\/header>/,header(prefix,current)).replace(/<footer[^>]*>[\s\S]*?<\/footer>/,footer(prefix)).replace(/<main>/,'<main id="main">');return s.replace(/\?v=im\d+/g,'?v=im23')}
// Render the public discovery surfaces from the same functions used by the browser.
for(const id of ['family-grid','featured-assets','sector-grid','software-count','prototype-count','research-count'])el(id);
context.api.overview(data);context.api.featured(data);
let home=read('templates/index.html');
for(const [id,e] of elements)if(e.innerHTML)home=home.replace(`<div class="${id==='family-grid'?'family-grid':id==='featured-assets'?'featured-grid':'sector-grid'}" id="${id}"></div>`,match=>match.replace('</div>',e.innerHTML+'</div>'));
write('index.html',shell(home,'',''));
elements.clear();for(const [id,value]of[['portfolio-schedule',''],['search',''],['sort','potential-desc'],['sector','all'],['family','all'],['filters',''],['result-count','']])el(id,value);
context.api.schedule(data);
let portfolio=read('templates/portfolio.html').replace(/<div class="schedule" id="portfolio-schedule">[\s\S]*?<\/div><\/div>/,`<div class="schedule" id="portfolio-schedule">${elements.get('portfolio-schedule').innerHTML}</div>`);
portfolio=portfolio.replace('<div class="filters" id="filters" aria-label="Development stage filters"></div>',`<div class="filters" id="filters" aria-label="Development stage filters">${elements.get('filters').innerHTML}</div>`);
for(const id of ['family','sector'])portfolio=portfolio.replace(new RegExp(`<select id="${id}">[\\s\\S]*?</select>`),`<select id="${id}">${elements.get(id).innerHTML}</select>`);
portfolio=portfolio.replace('<div class="tools tools-four">','<noscript><div class="notice">All 79 assets are listed below. Enable JavaScript to use search, sorting and filters.</div></noscript><div class="tools tools-four">');
write('portfolio.html',shell(portfolio,'','portfolio.html'));
for(const a of data.assets){elements.clear();const target=el('project');context.location.pathname=`/MyProjects/projects/${a.slug}/`;context.api.detail(data);let body=target.innerHTML;body=body.replace(/<header>[\s\S]*?<\/header>/,'').replace(/<footer[\s\S]*?<\/footer>/,'');body=body.replace('<div class="actions">',`${buyerPanel(a)}<div id="asset-economic-model">${context.economic.economicPanel(values.get(a.slug))}</div><div class="actions">`);
const title=escape(`${a.name} — Standalone IP Asset`),desc=escape(a.description);const html=`<!doctype html><html lang="en" data-data-path="../../assets/im-data.json"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#102c42"><title>${title}</title><meta name="description" content="${desc}"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><link rel="canonical" href="${base}projects/${a.slug}/"><link rel="stylesheet" href="../../assets/im4.css?v=im23"></head><body>${header('../../','portfolio.html')}<main id="main"><div id="project" data-rendered="true">${body}</div></main>${footer('../../')}<script src="../../assets/im.js?v=im23" defer></script><script src="../../assets/economic.js?v=im23" defer></script></body></html>`;write(`projects/${a.slug}/index.html`,html)}
guidePages['updates.html']={title:'Portfolio development review',eyebrow:'Repository snapshot · 9 September 2026',intro:'All 79 asset repositories reconciled against the commercial register. Current documentation was reviewed for 78 assets; one asset has metadata-only coverage. This is a dated review of default-branch information, not continuous monitoring or an independent technical audit.',sections:`<section class="shell section"><div class="notice"><strong>Reading this review.</strong> Latest repository activity may concern documentation or governance rather than a new capability. Where a README and later activity describe different baselines, the distinction is retained. Existing seller prices and commercial-stage classifications have not been automatically increased.</div><div class="diligence-grid development-grid">${data.assets.slice().sort((a,b)=>b.development.lastRepositoryActivity.localeCompare(a.development.lastRepositoryActivity)||a.ref.localeCompare(b.ref)).map(a=>`<article class="panel"><p class="eyebrow">${escape(a.ref)} · ${escape(a.development.lastRepositoryActivity)}</p><h2>${escape(a.name)}</h2><p>${escape(a.development.currentState)}</p><p class="fine">${escape(a.development.reviewBasis)}</p><a class="text-link" href="projects/${a.slug}/">Review asset →</a></article>`).join('')}</div></section>`};
for(const [route,page]of Object.entries(guidePages)){const families=data.families.map(f=>{const c=commercial.families[f.id];return `<article class="panel"><h3>${escape(f.name)}</h3><p><strong>Potential buyers:</strong> ${escape(c.buyers)}.</p><p><strong>Possible applications:</strong> ${escape(c.applications)}.</p><p>${escape(c.qualification)}</p><a class="text-link" href="portfolio.html?family=${encodeURIComponent(f.id)}">Review ${f.assets.length} individual assets →</a></article>`}).join('');const content=page.sections.replace('<!--FAMILY_CONTEXT-->',`<div class="diligence-grid">${families}</div>`);write(route,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(page.title)} — Technology & IP Portfolio</title><meta name="description" content="${escape(page.intro)}"><link rel="canonical" href="${base+route}"><link rel="stylesheet" href="assets/im4.css?v=im23"></head><body>${header('',route)}<main id="main"><section class="page-hero"><div class="shell"><p class="eyebrow">${escape(page.eyebrow)}</p><h1>${escape(page.title)}.</h1><p class="lede">${escape(page.intro)}</p></div></section>${content}</main>${footer('')}</body></html>`)}
for(const p of ['opportunity.html','valuation.html','evidence.html','transaction.html','notice.html'])write(p,shell(read(p),'',p).replace(/IM(?:18|19|20) (?:valuation context|evidence calibration)/g,'Current valuation context').replace('Five-lens economic model','Asset-level economic model').replace('Five lenses','Four valuation lenses and a separate asking price'));
console.log(`Built overview, searchable portfolio and ${data.assets.length} static profiles; three buyer guides and consistent navigation.`);
