import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const read=p=>fs.readFileSync(p,'utf8');
const assert=(ok,message)=>{if(!ok)throw Error(message)};
const pages=['index.html','portfolio.html','opportunity.html','valuation.html','evidence.html','transaction.html','notice.html','commercialization.html','assurance.html','transfer.html','updates.html',...fs.readdirSync('projects').map(p=>`projects/${p}/index.html`)];
for(const page of pages){const html=read(page);assert((html.match(/<h1[ >]/g)||[]).length===1,`One main heading: ${page}`);assert((html.match(/<main[ >]/g)||[]).length===1,`One main landmark: ${page}`);assert(html.includes('href="#main"'),'Skip link');assert(html.includes('aria-label="Primary navigation"'),'Labelled navigation');assert(html.includes('evidence.html">Evidence</a>'),`Evidence navigation: ${page}`);assert(!/€78\.5M|€47\.1M|€138\.3M/.test(html),`Superseded figures: ${page}`);assert(!html.includes('Loading standalone IP asset'),`Static asset profile: ${page}`);for(const m of html.matchAll(/(?:href|src)="([^"?#]+)(?:[?#][^"]*)?"/g)){let url=m[1].replaceAll('&amp;','&');if(/^(?:https?:|mailto:|data:)/.test(url))continue;const local=path.resolve(path.dirname(page),url);assert(fs.existsSync(local),`Missing local route or asset ${page}: ${url}`)}if(page.startsWith('projects/')){assert(html.includes('id="asset-economic-model"'),`Static economics: ${page}`);assert(!html.includes('<title>Standalone IP Asset —'),`Unique asset title: ${page}`);assert(html.includes(`href="https://thearchitect-max.github.io/MyProjects/${path.dirname(page)}/"`),`Absolute canonical: ${page}`)}}
assert((read('portfolio.html').match(/class="schedule-row"/g)||[]).length===79,'All 79 assets present without JavaScript');
assert(read('opportunity.html').includes('€71.598M')&&read('opportunity.html').includes('19.7%'),'Opportunity aligned');
// Exercise real filtering and sorting handlers without installing a browser or dependencies.
const elements=new Map();
for(const [id,value] of [['portfolio-schedule',''],['search',''],['sort','potential-desc'],['sector','all'],['family','all'],['filters',''],['result-count','']])elements.set(id,{value,innerHTML:'',textContent:'',handlers:{},addEventListener(type,fn){this.handlers[type]=fn},querySelectorAll(){return[]}});
const ctx={console,Intl,URLSearchParams,location:{search:'',pathname:'/'},document:{documentElement:{dataset:{}},getElementById:id=>elements.get(id)||null},fetch:async url=>({ok:true,json:async()=>JSON.parse(read(url.split('?')[0]))})};vm.createContext(ctx);vm.runInContext(read('assets/im.js').replace(/document.readyState==='loading'[\s\S]*?init\(\);\}\)\(\);\s*$/,'globalThis.api={load,schedule};})();'),ctx);
const data=await ctx.api.load();ctx.api.schedule(data);const change=(id,value,type='change')=>{const e=elements.get(id);e.value=value;e.handlers[type]()};const count=()=>elements.get('result-count').textContent;assert(count().startsWith('79 of'),'Initial asset count');change('search','TA-IP-072','input');assert(count().startsWith('1 of')&&elements.get('portfolio-schedule').innerHTML.includes('Adaptive Cognitive Runtime'),'Search by stable identifier');change('search','no-such-asset-zzzz','input');assert(count().startsWith('0 of')&&elements.get('portfolio-schedule').innerHTML.includes('No matching assets'),'Helpful empty state');change('search','','input');const family=data.families[0];change('family',family.id);assert(count().startsWith(`${data.assets.filter(a=>a.family.id===family.id).length} of`),'Family filter');change('family','all');const sector=data.assets[0].sector;change('sector',sector);assert(count().startsWith(`${data.assets.filter(a=>a.sector===sector).length} of`),'Sector filter');change('sector','all');change('sort','ask-asc');const first=data.assets.slice().sort((a,b)=>a.ask-b.ask)[0];assert(elements.get('portfolio-schedule').innerHTML.indexOf(first.ref)<elements.get('portfolio-schedule').innerHTML.indexOf(data.assets.find(a=>a.ask>first.ask).ref),'Price sorting');elements.get('filters').handlers.click({target:{closest:()=>({dataset:{filter:'R'}})}});assert(count().startsWith('6 of'),'Research-stage filter');
console.log(`Validated ${pages.length} active pages, local links, metadata, static profiles, consistent valuation figures, search, filters and sorting.`);

const review=JSON.parse(read('assets/development-status.json'));
assert(review.assets.length===79&&new Set(review.assets.map(a=>a.ref)).size===79,'Unique development records');
assert(review.assets.filter(a=>a.reviewBasis==='Repository metadata only').length===1,'One metadata-only review');
assert(review.documentationReviewed===78,'78 documentation reviews');
for(const a of review.assets){const html=read(`projects/${a.slug}/index.html`);assert(html.includes('Repository-reported position')&&html.includes(a.lastRepositoryActivity),'Dated development profile '+a.ref);assert(Object.keys(a).sort().join(',')==='currentState,lastRepositoryActivity,ref,reviewBasis,reviewedOn,slug','Public review allowlist '+a.ref);}
elements.get('filters').handlers.click({target:{closest:()=>({dataset:{filter:'all'}})}});change('search','clinical','input');assert(!count().startsWith('0 of'),'Search current development notes');
assert(read('updates.html').includes('metadata-only'),'Review coverage disclosure');
console.log('Development snapshot validated: 79 dated profiles, 78 document reviews, one metadata-only record, searchable current-state notes.');
