#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),json=p=>JSON.parse(read(p)),exists=p=>fs.existsSync(path.join(root,p)),assert=(c,m)=>{if(!c)throw new Error(m)};
const d=json('assets/im-data.json'),a=d.a,rc=json('assets/recreation-costs.json');
assert(d.v==='2026.09.06-im9'&&rc.v==='2026.09.06-im9','IM9 data versions');
assert(d.p[0]===69&&a.length===69&&rc.assets.length===69,'active asset count');
assert(new Set(a.map(x=>x[1])).size===69&&new Set(a.map(x=>x[2])).size===69,'unique refs/slugs');
assert(!a.some(x=>x[1]==='TA-IP-014'||x[2]==='aegis-vision-offline'),'withdrawn TA-IP-014 absent');
assert(a.some(x=>x[1]==='TA-IP-069'&&x[2]==='chimera-spectral-perception-system'),'TA-IP-069 retained');
assert(a.some(x=>x[1]==='TA-IP-070'&&x[2]==='hybrid-adaptive-rendering-media'),'TA-IP-070 HARM added');
assert(a.every(x=>/^TA-IP-\d{3}$/.test(x[1])),'reference format');assert(a.every(x=>x[1]===`TA-IP-${String(x[0]).padStart(3,'0')}`),'stable id/ref mapping');
a.forEach((x,i)=>{assert(x[9]<=x[8]&&x[8]<=x[10],`range ${x[1]}`);assert(Number(rc.assets[i])>0,`recreation ${x[1]}`);assert(!x[11],`stale external URL ${x[1]}`)});
const sum=i=>a.reduce((n,x)=>n+Number(x[i]),0),count=i=>a.reduce((m,x)=>(m[x[i]]=(m[x[i]]||0)+1,m),{});
assert(sum(8)===12245000&&sum(9)===9765000&&sum(10)===15330000,'portfolio values');assert(rc.portfolioRecreationCostEUR===49620000&&rc.assets.reduce((n,x)=>n+Number(x),0)===49620000,'recreation cost');
const sc=count(5),pc=count(6);assert(sc.V===37&&sc.P===27&&sc.R===5,'stage counts');assert(pc.VH===15&&pc.H===33&&pc.M===12&&pc.S===9,'potential counts');assert(d.fx[0]===1.1622&&d.fx[1]==='2026-09-04','FX');
const byRef=ref=>a.find(x=>x[1]===ref);
assert(JSON.stringify(byRef('TA-IP-010'))===JSON.stringify([10,'TA-IP-010','custody-integrity-assurance-platform','Custody Integrity Assurance Platform',3,'P','H',4,140000,110000,175000,'']),'TA-IP-010 CIAP contract');
assert(JSON.stringify(byRef('TA-IP-013'))===JSON.stringify([13,'TA-IP-013','evidence-governed-visual-intelligence-platform','AEGIS Vision — Evidence-Governed Visual Intelligence Platform',0,'V','VH',4,350000,280000,440000,'']),'TA-IP-013 EGVI contract');
assert(JSON.stringify(byRef('TA-IP-057'))===JSON.stringify([57,'TA-IP-057','autonomous-documentary-engine','Autonomous Documentary Engine',5,'V','VH',6,230000,185000,290000,'']),'TA-IP-057 contract');
assert(JSON.stringify(byRef('TA-IP-059'))===JSON.stringify([59,'TA-IP-059','fusionlunar-energy-systems-engineering-platform','FusionLunar Energy Systems Engineering Platform',6,'P','M',1,185000,145000,230000,'']),'TA-IP-059 contract');
assert(JSON.stringify(byRef('TA-IP-070'))===JSON.stringify([70,'TA-IP-070','hybrid-adaptive-rendering-media','HARM — Hybrid Adaptive Rendering & Media',5,'P','VH',6,160000,125000,200000,'']),'TA-IP-070 HARM contract');
for(const page of ['index.html','portfolio.html','opportunity.html','transaction.html','notice.html']){const h=read(page);assert(h.includes('Information Memorandum'),page);assert(h.includes('rel="canonical"'),`canonical ${page}`);assert(h.includes('im4.css?v=im9'),`IM9 cache ${page}`)}
const expected=new Set(a.map(x=>x[2])),actual=new Set(fs.readdirSync(path.join(root,'projects'),{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>x.name));assert(actual.size===expected.size,'project directory count');for(const x of expected)assert(actual.has(x),`missing project ${x}`);for(const x of actual)assert(expected.has(x),`stale project ${x}`);
for(const x of a){const p=`projects/${x[2]}/index.html`;assert(exists(p),`missing ${x[2]}`);const h=read(p);assert(h.includes('../../assets/im-data.json')&&h.includes('../../assets/im.js?v=im9')&&h.includes('../../assets/im4.css?v=im9')&&!h.includes('noindex'),`profile ${x[2]}`)}
const forbidden=['systemic-absolute-topology','lewis-hybrid-llm-orchestrator','sentinelbio-verify','agentic-engineering-control-plane','best-of-github-agentic-engineering','axiomcrypt','shield-breaker-research','titan-evtol-research-platform','avedi','biospeak','sovereign-commerce-engine','unified-execution-engine','aegis-vision-offline','unifiedcannabis','aegis-vision'];for(const x of forbidden)assert(!exists(`projects/${x}`),`withdrawn route ${x}`);
const locs=[...read('sitemap.xml').matchAll(/<loc>([^<]+)<\/loc>/g)].map(x=>x[1]);assert(locs.length===74&&new Set(locs).size===74,'sitemap');for(const x of a)assert(locs.includes(`https://thearchitect-max.github.io/MyProjects/projects/${x[2]}/`),`sitemap ${x[2]}`);assert(!locs.some(x=>x.includes('aegis-vision-offline')||x.includes('unifiedcannabis')||x.endsWith('/projects/aegis-vision/')),'withdrawn sitemap route');
const js=read('assets/im.js');new vm.Script(js,{filename:'assets/im.js'});assert(js.includes("const VERSION='im9'"),'IM9 runtime');assert(!js.includes('const aliases='),'legacy alias runtime removed');assert(!js.includes('SonicFabric-Site'),'stale SonicFabric link removed');
assert(!exists('evidence'),'evidence directory must not be in public tree');assert(!exists('.github/workflows'),'GitHub Actions workflows prohibited');
console.log(JSON.stringify({informationMemorandum:true,presentationRelease:'IM9',activeAssets:69,renamedReferences:{'TA-IP-010':'Custody Integrity Assurance Platform','TA-IP-013':'AEGIS Vision — Evidence-Governed Visual Intelligence Platform'},newReferences:{'TA-IP-070':'HARM — Hybrid Adaptive Rendering & Media'},withdrawnReferences:['TA-IP-014'],highestStableReference:'TA-IP-070',askingReferenceEUR:12245000,rangeEUR:[9765000,15330000],recreationCostEUR:49620000,stageCounts:{developedSoftware:37,developedPrototype:27,researchStage:5},potentialCounts:{veryHigh:15,high:33,moderate:12,specialist:9},sitemapUrls:74,staleProjectRoutes:0,staleExternalUrls:0,githubActions:false},null,2));
